### ISSUE TITLE
can i help?

### ISSUE THREAD

**Issue by Driesboy** [PrismarineMC/Prismarine#1]
#### OS and versions

* Prismarine:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MrGenga** [comment]
Yes you can, just create the pull request! :)

**Comment by Driesboy** [comment]
ok thx
but plz support 1.10.0 without update blocks and items
and plz make anvil support

**Comment by MrGenga** [comment]
@Driesboy first time, after Prismarine PC part relwased, it will be just changed BigBrother by @va2ron1 Then, I will be fix and fix and fix..... Did you create PR, hey?)
