### ISSUE TITLE
ChunkRequestTask: Task crashed...?

### ISSUE THREAD

**Issue by OtorisanVardo** [PrismarineMC/Prismarine#10]
#### Issue description

Below error happened when player joined server or canceled schedulerRepeatingTask.
it has a few type. so i don't know where problem is...   
Probably the error was happened by src.
please give me some advices!
  

#### Steps to reproduce the issue

happened when player joined server or canceled "schedulerRepeatingTask" or teleport..?
  

#### OS and versions

* Prismarine: 
  * Commit: c44fa14 ( Fixed PlayStatusPacket for old clients(HACK\!)  )
  * /version: Prismarine 1.2.0 Pumpkin Pie ~ API version 3.0.0 for Minecraft v1.2.0 (protocol version 137)
* PHP: 7.0
* Server OS: Windows (Linux(Ubuntu))
* Game version: v1.2.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Fatal error: Out of memory (allocated 8388608) (tried to allocate 131072 bytes) in ~\prismarine\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 70
Could not execute asynchronous task ChunkRequestTask: Task crashed
```

**Comment by Encritary** [comment]
It seems like you have not enough RAM. Try to make swapfile or something else and write back. If need, I will reopen the issue.
