### ISSUE TITLE
Setup wizard crashed.

### ISSUE THREAD

**Issue by famima65536** [PrismarineMC/Prismarine#11]
#### Issue description

Setup wizard crashed. 

#### Steps to reproduce the issue

Start the server in the initial state and set the language to "jpn".
Crash before choosing online mode.
#### OS and versions

* Prismarine: 
  commit: https://github.com/PrismarineMC/Prismarine/commit/1d6bb73b85fefeabb501b81adf914cb7235b2abd
  version: 
* PHP: PHP-7.0.14_Windows64
* Server OS: Windows10
* Game version: --

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Fatal error: Uncaught ErrorException: Undefined property: pocketmine\lang\BaseLang::$online_mode_info in C:\Users\{user}\Desktop\PocketMine\src\pocketmine\wizard\SetupWizard.php:140
Stack trace:
#0 C:\Users\{user}\Desktop\PocketMine\src\pocketmine\wizard\SetupWizard.php(140): pocketmine\{closure}(8, 'Undefined prope...', 'C:\\Users\\{user}\\...', 140, Array)
#1 C:\Users\{user}\Desktop\PocketMine\src\pocketmine\wizard\SetupWizard.php(84): pocketmine\wizard\SetupWizard->generateBaseConfig()
#2 C:\Users\{user}\Desktop\PocketMine\src\pocketmine\PocketMine.php(499): pocketmine\wizard\SetupWizard->run()
#3 {main}
  thrown in C:\Users\tokai\Desktop\PocketMine\src\pocketmine\wizard\SetupWizard.php on line 140

```

**Comment by Encritary** [comment]
I will fix it.

**Comment by CasperVanNeck** [comment]
fixt
