### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by NycuRO** [PrismarineMC/Prismarine#12]
SPAM

**Comment by TheDiamondYT1** [comment]
This is not related to Prismarine.

**Comment by CasperVanNeck** [comment]
Stop with opning it its spam done

**Comment by NycuRO** [comment]
@RedstoneAlmeida dude, you suck.

**Comment by CasperVanNeck** [comment]
Just stop its spam

**Comment by xISRAPILx** [comment]
Facked schoolboy!

**Comment by NycuRO** [comment]
Spammm, yayyyy

**Comment by xISRAPILx** [comment]
@Encritary УДАЛИ ЕГО ИЗ РЕПО, БЛЯ

**Comment by NycuRO** [comment]
hello again 🗡

**Comment by mal0ne-23** [comment]
@NycuRO You're a cunt, stop wasting your time bothering people that play minecraft. That's really low.

**Comment by CasperVanNeck** [comment]
Stop it @NycuRO
