### ISSUE TITLE
Problem with inventory (mcpe 1.1)

### ISSUE THREAD

**Issue by AlllDev** [PrismarineMC/Prismarine#13]
I use Prismarine mcpe 1.1 version (not 1.2), the last version. I have a problem with player inventory.
1.The problem with saving player, player didnt save and in console write a error-mesage with BaseInventory.php on line 108 assert($index >= 0, "Inventory slot should not be negative"); and i delete this line.
2.I use a Minecraft PE 1.1.9 version, in pocket-interface, when i trying change item in held, which have item, i cannot this, proccess canceled  on inventory and item which been in a slot return, in a classic-interface-minecraft this problem does not arise.
3.This problem arises when a delete 108 line on BaseInventory.php (assert($index >= 0, "Inventory slot should not be negative");

**Comment by Encritary** [comment]
1.1 abandoded
