### ISSUE TITLE
Server List Display Bug

### ISSUE THREAD

**Issue by Nerahikada** [PrismarineMC/Prismarine#14]
#### Issue description

The display with other servers will be mixed or offline display will be displayed.
#### Steps to reproduce the issue

It's uncertain...
#### OS and versions

* Prismarine: https://github.com/PrismarineMC/Prismarine/commit/3f4812ada044f3e507ad1ee7c8f832867c56f1cf
* PHP: 7.0.14
* Server OS: anything
* Game version: 1.2.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Encritary** [comment]
1.2 bug

**Comment by Nerahikada** [comment]
It's not 1.2 bug.
This is because I can't reproduce it with [PocketMine-MP](https://github.com/pmmp/PocketMine-MP).
And I think that this is the cause, [pocketmine\network\mcpe\RaklibInterface.php in line 182](https://github.com/PrismarineMC/Prismarine/blob/master/src/pocketmine/network/mcpe/RakLibInterface.php#L182).

**Comment by Hatsune-Miku1012** [comment]
its not what ever

**Comment by Hatsune-Miku1012** [comment]
i dont have it

**Comment by Nerahikada** [comment]
I think maybe it's not 1.2 bug.
This is because I can't reproduce it using [PocketMine-MP](https://github.com/pmmp/PocketMine-MP).

**Comment by Nerahikada** [comment]
https://github.com/PrismarineMC/Prismarine/blob/master/src/pocketmine/network/mcpe/RakLibInterface.php#L182

This must be the server id.
