### ISSUE TITLE
what fuck do i rong 

### ISSUE THREAD

**Issue by caspervanneck** [PrismarineMC/Prismarine#15]
what do i rong and shut upp with blame my the holl time   im realy angry  @MrGenga

**Comment by caspervanneck** [comment]
ps kanker op

**Comment by caspervanneck** [comment]
what fo i rong say it yo my ):

**Comment by MrGenga** [comment]
@caspervanneck sorry for my angry. But for the future: do not do things, what brokes compatible with Genisys, ok?

**Comment by caspervanneck** [comment]
yes @MrGenga
