### ISSUE TITLE
Support for 0.15.9 0.16.0

### ISSUE THREAD

**Issue by caspervanneck** [PrismarineMC/Prismarine#16]
Like stead fast or genisys

**Comment by MrKiaN** [comment]
Hi , Are This Support For 0.15.6 or 0.15.7?

**Comment by caspervanneck** [comment]
not jet @MrKiaN

**Comment by MrKiaN** [comment]
ok Thanks

**Comment by MrKiaN** [comment]
Plzz Answer I need Help:-D

**Comment by caspervanneck** [comment]
@mrkian yes pm plugins are suported

**Comment by MrKiaN** [comment]
WoW Thats Amazing, i have another question 😁, why in creative  dont a item or block? are this need command , sry for my english (im iranian)

**Comment by TiesGamesNL** [comment]
@MrKiaN @caspervanneck is dutch ;)

**Comment by MrGenga** [comment]
It is already support latest 1.0.0! :)
