### ISSUE TITLE
WindowInventory Work?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [PrismarineMC/Prismarine#17]
#### Issue description

Is Work? i'm making plugin /chest using WindowInventory
#### OS and versions

- Prismarine:
- PHP:
- Server OS:
- Game version: 
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
Idk

**Comment by RedstoneAlmeida** [comment]
?

**Comment by caspervanneck** [comment]
i dont know = idk @RedstoneAlmeida

**Comment by RedstoneAlmeida** [comment]
oh, i'm speak portuguese, sorry <3

i'm have tested a code is crashed my Minecraft Window 10 Edition

**Comment by MrGenga** [comment]
Yes it is working!
