### ISSUE TITLE
HERES SUPPORT FOR PC WITH BUG THROUGH LIKE LEFT/RIGHT CLICK SUPPORT ADDS  DISCONECTIION TO CLIENT AND NEEDS COMMANDS AND BLANK SIGN BUG BUT WORKS FULLY

### ISSUE THREAD

**Issue by matthew4444** [PrismarineMC/Prismarine#18]
here pc support https://github.com/NycuRO/BigBrother
read me first:
HERES SUPPORT FOR PC WITH BUG THROUGH ,WHEN PC USR DOES THE LEFT/RIGHT CLICK SUPPORT ADDS  DISCONECTIION TO CLIENT ,AND NEEDS COMMANDS AND BLANK SIGN BUG BUT WORKS FULLY OTHERWISE.
NEED TO FIX BUGS  BEFORE INCOPERATING THIS IN THIS SOFTWARE ,PLZ AADD THIS AS A PC SUPOORT PLZ , NEEDS BUG FIXING, THANKS

**Comment by caspervanneck** [comment]
spam
