### ISSUE TITLE
Can i be in this dev team plz, i want to give advice and great plugins and links plz

### ISSUE THREAD

**Issue by matthew4444** [PrismarineMC/Prismarine#19]
Can i be in this dev team plz, i want to give advice and great plugins and links plz, and im very good at web servers and websites

**Comment by matthew4444** [comment]
gotta go to school tomoorw sorry,and imm a better typer,when im not typing fast,gtg today srry ,bye

**Comment by MrGenga** [comment]
Maybe, create PR, I see what you can

**Comment by MrGenga** [comment]
So... No
