### ISSUE TITLE
Conexion error and raklib

### ISSUE THREAD

**Issue by NycuRO** [PrismarineMC/Prismarine#2]
#### Issue description

Hello. Not all person know this bug,but probably you need fix for players with conexion :-1:  .

Raklib Genisys is very buggy and have bug with error chunks. Yes,is ambiguous. I know is from raklib ( i test with my project Apollo ,base of Genisys ) and i'm changed raklib genisys with steadfight2. Genisys raklib is buggy and if you enter in server,you get in void or not chunks loaded.

IS NOT WORLD PROBLEM OR CHUNKS FILE.

Not all have this bug,but have much players with conexion :-1:  .

If you want to fix,need copy-paste steadfight2 raklib with genisys :)
#### Steps to reproduce the issue

Enter in server and get issue.
#### OS and versions

* Prismarine: https://github.com/PrismarineMC/Prismarine/commit/f0553880eb882d27e824824d90376216fa9fba31
* PHP: 7.0.10
* Server OS: Debian 8 64Bit Minimal and Ubuntuu 14.04.5 64bit 
* Game version: 0.15.6 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MrGenga** [comment]
@NycuRO you can join Prismarine Team and put all your features into Prismarine. Just tell me about that. I welcome new members to team

**Comment by MrGenga** [comment]
@NycuRO I see you have created very stable core. Let's continue development of this here, because I collecting team to create the best server software for MCPE and MCPC(in the future). Did you enter the team and push all(or part by part) your improvements to Prismarine? I hope you agree.

**Comment by NycuRO** [comment]
@MrGenga No,srry. Momentaly,need start dev plugins. Server software is very hard for developing and i don't have time. If you need help,ask me :)

**Comment by NycuRO** [comment]
@MrGenga 
I would be very happy if you could solve the synapsa bug , bug genisys we reported here : https://github.com/iTXTech/Genisys/issues/1782 :)
