### ISSUE TITLE
Question LevelDB

### ISSUE THREAD

**Issue by NycuRO** [PrismarineMC/Prismarine#20]
I want to create generator generation on LevelBD.

Why LevelBD?

LevelBD is official MCPE ,for MCPE and have more performance.

You can watch performance and code here : https://github.com/Mojang/leveldb-mcpe

MCPE have LevelBD, not Anvil or Region. If you like this ''features'' ,i want to create official generation in levelbd ;)

**Comment by MrGenga** [comment]
It requiers special extension for php, I don't know. There is no src for MCPE, C++ can't be decompiled

**Comment by NycuRO** [comment]
@MrGenga But translate from c++ in php :)

**Comment by MrGenga** [comment]
@NycuRO C++ can't be decompiled!
