### ISSUE TITLE
This project is illegal

### ISSUE THREAD

**Issue by Monkeyboy2805** [PrismarineMC/Prismarine#23]
#### Issue description

Prismarine has been trademarked by Mojang. YOU NEED TO RENAME THIS PROJECT OR MOJANG MAY DMCA YOU!

#### OS and versions

* Prismarine:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
shut up it abandon

**Comment by DaMatrix** [comment]
@Monkeyboy2805 i can tell that.

**Comment by Monkeyboy2805** [comment]
@DaMatrix That was because @caspervanneck changed it. @caspervanneck nob
