### ISSUE TITLE
whatz linux edition?

### ISSUE THREAD

**Issue by matthew4444** [PrismarineMC/Prismarine#25]
#### Issue description

i have linux, on my pc, but what type of edition is it, is it minecraft pc edition in java in linux?
#### OS and versions

* Prismarine:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DaMatrix** [comment]
Prismarine is a pocket edition server software. 

-------- Original message --------

**Comment by matthew4444** [comment]
so why put linux edittion if it says supports mcpe and windoes 10?

**Comment by DaMatrix** [comment]
You run the server on Linux. You play on mcpe. Is it that complex?

**Comment by DaMatrix** [comment]
I think what they meant was mcpelauncher-linux, a way to launch mcpe on Linux.

**Comment by matthew4444** [comment]
Ik what that is, though, i have it dualbooted , windows and linux and u use windoes 10 edition , andjava pc edition in linux, and pe with bluestacks in windows, thx
