### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by NycuRO** [PrismarineMC/Prismarine#33]
Why you want that, lol, 1.1.x was rip.

Why you don't create a 1.2 software?

**Comment by xISRAPILx** [comment]
In the Russian MCPE, many players stayed at 1.1, due to the fact that in 1.2 it is necessary to buy a license or to crack a license (the players are lazy). @NycuRO

**Comment by Encritary** [comment]
Use pmmp for 1.2. @xISRAPILx the players is *DUMB*

**Comment by xISRAPILx** [comment]
@Encritary no, you stupid!
