### ISSUE TITLE
1.2 Support?

### ISSUE THREAD

**Issue by XDqrkneZ** [PrismarineMC/Prismarine#6]
#### Issue description

does it support the new 1.2 update?

#### OS and versions

* Prismarine:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Encritary** [comment]
Yes it does, check mcpe1?2, I will commit release protocol update immediatly.

**Comment by Encritary** [comment]
Done
