### ISSUE TITLE
Generator

### ISSUE THREAD

**Issue by NycuRO** [PrismarineMC/Prismarine#8]
Is not one issue. I can add my generator from Apollo to Prismarine ? 

I have to continue to develop Apollo , but only the generator else. I wanted to add generator in Prismarine and you have developed at the bugs and the rest . What do you say? :)

**Comment by RedstoneAlmeida** [comment]
Create a New branch to your project, and test :+1:

**Comment by NycuRO** [comment]
I'm colaborator? @MrGenga ? I'm starting next day. :)

**Comment by NycuRO** [comment]
@MrGenga I can can help you with generator. You can me add collaborator?

**Comment by NycuRO** [comment]
Thanks for collaborator @MrGenga
