### ISSUE TITLE
API? 

### ISSUE THREAD

**Issue by LolNova** [PrismarineMC/Prismarine#9]
What api does this software use? 😄

**Comment by TheDiamondYT1** [comment]
?

**Comment by LolNova** [comment]
does it use api 2.0.0? 3.0.0?

**Comment by TheDiamondYT1** [comment]
spoons are evil. https://github.com/PrismarineMC/Prismarine/blob/a2678e8e649415cc2911456b6904f402973eeb47/src/pocketmine/PocketMine.php#L82
